// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgqrmktmkdnuarvloqnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpncXJta3Rta2RudWFydmxvcW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1OTAyNDksImV4cCI6MjA1NjE2NjI0OX0.HYIotvHZnDNqQ4yaLNt0Of0g290zaXfDxuB0XGfalXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);